apiVersion: v1
kind: Service
metadata:
  name: marketalerts-ui
  namespace: marketalerts-ui
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: marketalerts-ui